services:
  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yapper
      POSTGRES_PASSWORD: passw0rd
    # volumes:
    #   - db_data:/var/lib/postgresql/data
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
# volumes:
# db_data:
