// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: media.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    type,
    url,
    content_id,
    content_type
) VALUES (
    $1, $2, $3, $4
) RETURNING media_id, type, url, content_id, content_type, created_at, deleted_at
`

type CreateMediaParams struct {
	Type        string
	Url         string
	ContentID   pgtype.UUID
	ContentType pgtype.Text
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.Type,
		arg.Url,
		arg.ContentID,
		arg.ContentType,
	)
	var i Medium
	err := row.Scan(
		&i.MediaID,
		&i.Type,
		&i.Url,
		&i.ContentID,
		&i.ContentType,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT media_id, type, url, content_id, content_type, created_at, deleted_at FROM media
WHERE media_id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetMediaByID(ctx context.Context, mediaID pgtype.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, mediaID)
	var i Medium
	err := row.Scan(
		&i.MediaID,
		&i.Type,
		&i.Url,
		&i.ContentID,
		&i.ContentType,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaForContent = `-- name: GetMediaForContent :many
SELECT media_id, type, url, content_id, content_type, created_at, deleted_at FROM media
WHERE content_id = $1
AND content_type = $2
AND deleted_at IS NULL
ORDER BY created_at ASC
`

type GetMediaForContentParams struct {
	ContentID   pgtype.UUID
	ContentType pgtype.Text
}

func (q *Queries) GetMediaForContent(ctx context.Context, arg GetMediaForContentParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, getMediaForContent, arg.ContentID, arg.ContentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.MediaID,
			&i.Type,
			&i.Url,
			&i.ContentID,
			&i.ContentType,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrphanedMedia = `-- name: GetOrphanedMedia :many
SELECT media_id, type, url, content_id, content_type, created_at, deleted_at FROM media
WHERE content_id IS NULL
AND deleted_at IS NULL
AND created_at < $1
`

func (q *Queries) GetOrphanedMedia(ctx context.Context, createdAt pgtype.Timestamptz) ([]Medium, error) {
	rows, err := q.db.Query(ctx, getOrphanedMedia, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.MediaID,
			&i.Type,
			&i.Url,
			&i.ContentID,
			&i.ContentType,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnassociatedMediaByID = `-- name: GetUnassociatedMediaByID :one
SELECT media_id, type, url, content_id, content_type, created_at, deleted_at FROM media
WHERE media_id = $1
AND content_id IS NULL
AND content_type IS NULL
AND deleted_at IS NULL
`

func (q *Queries) GetUnassociatedMediaByID(ctx context.Context, mediaID pgtype.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getUnassociatedMediaByID, mediaID)
	var i Medium
	err := row.Scan(
		&i.MediaID,
		&i.Type,
		&i.Url,
		&i.ContentID,
		&i.ContentType,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteSoftDeletedMedia = `-- name: HardDeleteSoftDeletedMedia :exec
DELETE FROM media
WHERE deleted_at IS NOT NULL
AND deleted_at < $1
`

func (q *Queries) HardDeleteSoftDeletedMedia(ctx context.Context, deletedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, hardDeleteSoftDeletedMedia, deletedAt)
	return err
}

const orphanMedia = `-- name: OrphanMedia :exec
UPDATE media
SET content_id = NULL,
    content_type = NULL
WHERE content_id = $1
AND content_type = $2
AND deleted_at IS NULL
`

type OrphanMediaParams struct {
	ContentID   pgtype.UUID
	ContentType pgtype.Text
}

func (q *Queries) OrphanMedia(ctx context.Context, arg OrphanMediaParams) error {
	_, err := q.db.Exec(ctx, orphanMedia, arg.ContentID, arg.ContentType)
	return err
}

const softDeleteMedia = `-- name: SoftDeleteMedia :exec
UPDATE media
SET deleted_at = NOW()
WHERE media_id = $1
`

func (q *Queries) SoftDeleteMedia(ctx context.Context, mediaID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMedia, mediaID)
	return err
}

const updateMediaContent = `-- name: UpdateMediaContent :exec
UPDATE media
SET content_id = $1,
    content_type = $2
WHERE media_id = $3
AND content_id IS NULL
AND content_type IS NULL
AND deleted_at IS NULL
`

type UpdateMediaContentParams struct {
	ContentID   pgtype.UUID
	ContentType pgtype.Text
	MediaID     pgtype.UUID
}

func (q *Queries) UpdateMediaContent(ctx context.Context, arg UpdateMediaContentParams) error {
	_, err := q.db.Exec(ctx, updateMediaContent, arg.ContentID, arg.ContentType, arg.MediaID)
	return err
}
