// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActiveUser struct {
	UserID    pgtype.UUID
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Medium struct {
	MediaID     pgtype.UUID
	Type        string
	Url         string
	ContentID   pgtype.UUID
	ContentType pgtype.Text
	CreatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type User struct {
	UserID    pgtype.UUID
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Yap struct {
	YapID         pgtype.UUID
	UserID        pgtype.UUID
	Content       string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	Hashtags      []string
	Mentions      []string
	LocationPoint interface{}
}
