// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateYap(ctx context.Context, arg CreateYapParams) (CreateYapRow, error)
	DeleteUser(ctx context.Context, userID pgtype.UUID) error
	DeleteYap(ctx context.Context, arg DeleteYapParams) error
	GetMediaByID(ctx context.Context, mediaID pgtype.UUID) (Medium, error)
	GetMediaForContent(ctx context.Context, arg GetMediaForContentParams) ([]Medium, error)
	GetOrphanedMedia(ctx context.Context, createdAt pgtype.Timestamptz) ([]Medium, error)
	GetUnassociatedMediaByID(ctx context.Context, mediaID pgtype.UUID) (Medium, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetYapByID(ctx context.Context, yapID pgtype.UUID) (GetYapByIDRow, error)
	HardDeleteSoftDeletedMedia(ctx context.Context, deletedAt pgtype.Timestamptz) error
	ListYapsByUser(ctx context.Context, arg ListYapsByUserParams) ([]ListYapsByUserRow, error)
	NewUser(ctx context.Context, arg NewUserParams) (pgtype.UUID, error)
	OrphanMedia(ctx context.Context, arg OrphanMediaParams) error
	SoftDeleteMedia(ctx context.Context, mediaID pgtype.UUID) error
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (User, error)
	UpdateMediaContent(ctx context.Context, arg UpdateMediaContentParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateYap(ctx context.Context, arg UpdateYapParams) (UpdateYapRow, error)
}

var _ Querier = (*Queries)(nil)
