// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: yaps.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createYap = `-- name: CreateYap :one
INSERT INTO yaps (
  user_id,
  content,
  hashtags,
  mentions,
  location_point
) VALUES (
  $1, $2, $3, $4,
  CASE
    WHEN $5::DOUBLE PRECISION IS NOT NULL AND $6::DOUBLE PRECISION IS NOT NULL
    THEN ST_SetSRID(ST_MakePoint($6::DOUBLE PRECISION, $5::DOUBLE PRECISION), 4326)
    ELSE NULL
  END
)
RETURNING
  yap_id,
  user_id,
  content,
  hashtags,
  mentions,
  ST_X(location_point::geometry) as longitude,
  ST_Y(location_point::geometry) as latitude,
  created_at,
  updated_at
`

type CreateYapParams struct {
	UserID   pgtype.UUID
	Content  string
	Hashtags []string
	Mentions []string
	Column5  float64
	Column6  float64
}

type CreateYapRow struct {
	YapID     pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	Hashtags  []string
	Mentions  []string
	Longitude interface{}
	Latitude  interface{}
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateYap(ctx context.Context, arg CreateYapParams) (CreateYapRow, error) {
	row := q.db.QueryRow(ctx, createYap,
		arg.UserID,
		arg.Content,
		arg.Hashtags,
		arg.Mentions,
		arg.Column5,
		arg.Column6,
	)
	var i CreateYapRow
	err := row.Scan(
		&i.YapID,
		&i.UserID,
		&i.Content,
		&i.Hashtags,
		&i.Mentions,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteYap = `-- name: DeleteYap :exec
UPDATE yaps
SET deleted_at = NOW()
WHERE yap_id = $1
AND user_id = $2
AND deleted_at IS NULL
`

type DeleteYapParams struct {
	YapID  pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteYap(ctx context.Context, arg DeleteYapParams) error {
	_, err := q.db.Exec(ctx, deleteYap, arg.YapID, arg.UserID)
	return err
}

const getYapByID = `-- name: GetYapByID :one
SELECT yap_id,
       user_id,
       content,
       hashtags,
       mentions,
       ST_X(location_point::geometry) as longitude,
       ST_Y(location_point::geometry) as latitude,
       created_at,
       updated_at
FROM yaps
WHERE yap_id = $1 AND deleted_at IS NULL
`

type GetYapByIDRow struct {
	YapID     pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	Hashtags  []string
	Mentions  []string
	Longitude interface{}
	Latitude  interface{}
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetYapByID(ctx context.Context, yapID pgtype.UUID) (GetYapByIDRow, error) {
	row := q.db.QueryRow(ctx, getYapByID, yapID)
	var i GetYapByIDRow
	err := row.Scan(
		&i.YapID,
		&i.UserID,
		&i.Content,
		&i.Hashtags,
		&i.Mentions,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listYapsByUser = `-- name: ListYapsByUser :many
SELECT yap_id,
       user_id,
       content,
       hashtags,
       mentions,
       ST_X(location_point::geometry) as longitude,
       ST_Y(location_point::geometry) as latitude,
       created_at,
       updated_at
FROM yaps
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT COALESCE($2, 20) OFFSET COALESCE($3, 0)
`

type ListYapsByUserParams struct {
	UserID  pgtype.UUID
	Column2 interface{}
	Column3 interface{}
}

type ListYapsByUserRow struct {
	YapID     pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	Hashtags  []string
	Mentions  []string
	Longitude interface{}
	Latitude  interface{}
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListYapsByUser(ctx context.Context, arg ListYapsByUserParams) ([]ListYapsByUserRow, error) {
	rows, err := q.db.Query(ctx, listYapsByUser, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListYapsByUserRow
	for rows.Next() {
		var i ListYapsByUserRow
		if err := rows.Scan(
			&i.YapID,
			&i.UserID,
			&i.Content,
			&i.Hashtags,
			&i.Mentions,
			&i.Longitude,
			&i.Latitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateYap = `-- name: UpdateYap :one
UPDATE yaps
SET
    content = CASE
        WHEN $2::text IS NOT NULL THEN $2::text
        ELSE content
    END,
    hashtags = CASE
        WHEN $3::text[] IS NOT NULL THEN $3::text[]
        ELSE hashtags
    END,
    mentions = CASE
        WHEN $4::text[] IS NOT NULL THEN $4::text[]
        ELSE mentions
    END,
    location_point = CASE
        WHEN $5::DOUBLE PRECISION IS NOT NULL AND $6::DOUBLE PRECISION IS NOT NULL
        AND ($5::DOUBLE PRECISION != 0 OR $6::DOUBLE PRECISION != 0)
        THEN ST_SetSRID(ST_MakePoint($6::DOUBLE PRECISION, $5::DOUBLE PRECISION), 4326)
        WHEN $7::boolean THEN NULL
        ELSE location_point
    END
WHERE yap_id = $1
    AND user_id = $8
    AND deleted_at IS NULL
RETURNING yap_id,
          user_id,
          content,
          hashtags,
          mentions,
          ST_X(location_point::geometry) as longitude,
          ST_Y(location_point::geometry) as latitude,
          created_at,
          updated_at
`

type UpdateYapParams struct {
	YapID   pgtype.UUID
	Column2 string
	Column3 []string
	Column4 []string
	Column5 float64
	Column6 float64
	Column7 bool
	UserID  pgtype.UUID
}

type UpdateYapRow struct {
	YapID     pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	Hashtags  []string
	Mentions  []string
	Longitude interface{}
	Latitude  interface{}
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateYap(ctx context.Context, arg UpdateYapParams) (UpdateYapRow, error) {
	row := q.db.QueryRow(ctx, updateYap,
		arg.YapID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.UserID,
	)
	var i UpdateYapRow
	err := row.Scan(
		&i.YapID,
		&i.UserID,
		&i.Content,
		&i.Hashtags,
		&i.Mentions,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
