// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	media "github.com/chocological13/yapper-backend/pkg/media"
	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	pgtype "github.com/jackc/pgx/v5/pgtype"

	pgx "github.com/jackc/pgx/v5"

	repository "github.com/chocological13/yapper-backend/pkg/database/repository"
)

// MediaService is an autogenerated mock type for the MediaService type
type MediaService struct {
	mock.Mock
}

// CleanUpOrphanedMedia provides a mock function with given fields: ctx
func (_m *MediaService) CleanUpOrphanedMedia(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanUpOrphanedMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMediaByID provides a mock function with given fields: ctx, mediaID
func (_m *MediaService) GetMediaByID(ctx context.Context, mediaID pgtype.UUID) (*repository.Medium, error) {
	ret := _m.Called(ctx, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaByID")
	}

	var r0 *repository.Medium
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (*repository.Medium, error)); ok {
		return rf(ctx, mediaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) *repository.Medium); ok {
		r0 = rf(ctx, mediaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Medium)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, mediaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnassociatedMediaByID provides a mock function with given fields: ctx, mediaID
func (_m *MediaService) GetUnassociatedMediaByID(ctx context.Context, mediaID pgtype.UUID) (*repository.Medium, error) {
	ret := _m.Called(ctx, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnassociatedMediaByID")
	}

	var r0 *repository.Medium
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (*repository.Medium, error)); ok {
		return rf(ctx, mediaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) *repository.Medium); ok {
		r0 = rf(ctx, mediaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Medium)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, mediaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HardDeleteSoftDeletedMedia provides a mock function with given fields: ctx
func (_m *MediaService) HardDeleteSoftDeletedMedia(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteSoftDeletedMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListByContent provides a mock function with given fields: ctx, contentID, contentType
func (_m *MediaService) ListByContent(ctx context.Context, contentID pgtype.UUID, contentType string) ([]*repository.Medium, error) {
	ret := _m.Called(ctx, contentID, contentType)

	if len(ret) == 0 {
		panic("no return value specified for ListByContent")
	}

	var r0 []*repository.Medium
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) ([]*repository.Medium, error)); ok {
		return rf(ctx, contentID, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) []*repository.Medium); ok {
		r0 = rf(ctx, contentID, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.Medium)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, string) error); ok {
		r1 = rf(ctx, contentID, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrphanMedia provides a mock function with given fields: ctx, mediaID, contentType
func (_m *MediaService) OrphanMedia(ctx context.Context, mediaID pgtype.UUID, contentType string) error {
	ret := _m.Called(ctx, mediaID, contentType)

	if len(ret) == 0 {
		panic("no return value specified for OrphanMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) error); ok {
		r0 = rf(ctx, mediaID, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMediaContent provides a mock function with given fields: ctx, yapID, mediaID, contentType
func (_m *MediaService) UpdateMediaContent(ctx context.Context, yapID pgtype.UUID, mediaID pgtype.UUID, contentType string) error {
	ret := _m.Called(ctx, yapID, mediaID, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMediaContent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID, string) error); ok {
		r0 = rf(ctx, yapID, mediaID, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadMedia provides a mock function with given fields: ctx, file, folderName
func (_m *MediaService) UploadMedia(ctx context.Context, file *multipart.FileHeader, folderName string) (*repository.Medium, error) {
	ret := _m.Called(ctx, file, folderName)

	if len(ret) == 0 {
		panic("no return value specified for UploadMedia")
	}

	var r0 *repository.Medium
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, string) (*repository.Medium, error)); ok {
		return rf(ctx, file, folderName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, string) *repository.Medium); ok {
		r0 = rf(ctx, file, folderName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Medium)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader, string) error); ok {
		r1 = rf(ctx, file, folderName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTx provides a mock function with given fields: tx
func (_m *MediaService) WithTx(tx pgx.Tx) media.MediaService {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 media.MediaService
	if rf, ok := ret.Get(0).(func(pgx.Tx) media.MediaService); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(media.MediaService)
		}
	}

	return r0
}

// NewMediaService creates a new instance of MediaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaService {
	mock := &MediaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
