// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/chocological13/yapper-backend/pkg/database/repository"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

// CreateMedia provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateMedia(ctx context.Context, arg repository.CreateMediaParams) (repository.Medium, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateMedia")
	}

	var r0 repository.Medium
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateMediaParams) (repository.Medium, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateMediaParams) repository.Medium); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Medium)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateMediaParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateYap provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateYap(ctx context.Context, arg repository.CreateYapParams) (repository.CreateYapRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateYap")
	}

	var r0 repository.CreateYapRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateYapParams) (repository.CreateYapRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateYapParams) repository.CreateYapRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.CreateYapRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateYapParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *Querier) DeleteUser(ctx context.Context, userID pgtype.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteYap provides a mock function with given fields: ctx, arg
func (_m *Querier) DeleteYap(ctx context.Context, arg repository.DeleteYapParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteYap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteYapParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMediaByID provides a mock function with given fields: ctx, mediaID
func (_m *Querier) GetMediaByID(ctx context.Context, mediaID pgtype.UUID) (repository.Medium, error) {
	ret := _m.Called(ctx, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaByID")
	}

	var r0 repository.Medium
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (repository.Medium, error)); ok {
		return rf(ctx, mediaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) repository.Medium); ok {
		r0 = rf(ctx, mediaID)
	} else {
		r0 = ret.Get(0).(repository.Medium)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, mediaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMediaForContent provides a mock function with given fields: ctx, arg
func (_m *Querier) GetMediaForContent(ctx context.Context, arg repository.GetMediaForContentParams) ([]repository.Medium, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaForContent")
	}

	var r0 []repository.Medium
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetMediaForContentParams) ([]repository.Medium, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetMediaForContentParams) []repository.Medium); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Medium)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetMediaForContentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrphanedMedia provides a mock function with given fields: ctx, createdAt
func (_m *Querier) GetOrphanedMedia(ctx context.Context, createdAt pgtype.Timestamptz) ([]repository.Medium, error) {
	ret := _m.Called(ctx, createdAt)

	if len(ret) == 0 {
		panic("no return value specified for GetOrphanedMedia")
	}

	var r0 []repository.Medium
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Timestamptz) ([]repository.Medium, error)); ok {
		return rf(ctx, createdAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Timestamptz) []repository.Medium); ok {
		r0 = rf(ctx, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Medium)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.Timestamptz) error); ok {
		r1 = rf(ctx, createdAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnassociatedMediaByID provides a mock function with given fields: ctx, mediaID
func (_m *Querier) GetUnassociatedMediaByID(ctx context.Context, mediaID pgtype.UUID) (repository.Medium, error) {
	ret := _m.Called(ctx, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnassociatedMediaByID")
	}

	var r0 repository.Medium
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (repository.Medium, error)); ok {
		return rf(ctx, mediaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) repository.Medium); ok {
		r0 = rf(ctx, mediaID)
	} else {
		r0 = ret.Get(0).(repository.Medium)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, mediaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, arg
func (_m *Querier) GetUser(ctx context.Context, arg repository.GetUserParams) (repository.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetUserParams) (repository.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetUserParams) repository.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetYapByID provides a mock function with given fields: ctx, yapID
func (_m *Querier) GetYapByID(ctx context.Context, yapID pgtype.UUID) (repository.GetYapByIDRow, error) {
	ret := _m.Called(ctx, yapID)

	if len(ret) == 0 {
		panic("no return value specified for GetYapByID")
	}

	var r0 repository.GetYapByIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (repository.GetYapByIDRow, error)); ok {
		return rf(ctx, yapID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) repository.GetYapByIDRow); ok {
		r0 = rf(ctx, yapID)
	} else {
		r0 = ret.Get(0).(repository.GetYapByIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, yapID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HardDeleteSoftDeletedMedia provides a mock function with given fields: ctx, deletedAt
func (_m *Querier) HardDeleteSoftDeletedMedia(ctx context.Context, deletedAt pgtype.Timestamptz) error {
	ret := _m.Called(ctx, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteSoftDeletedMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Timestamptz) error); ok {
		r0 = rf(ctx, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListYapsByUser provides a mock function with given fields: ctx, arg
func (_m *Querier) ListYapsByUser(ctx context.Context, arg repository.ListYapsByUserParams) ([]repository.ListYapsByUserRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListYapsByUser")
	}

	var r0 []repository.ListYapsByUserRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListYapsByUserParams) ([]repository.ListYapsByUserRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListYapsByUserParams) []repository.ListYapsByUserRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ListYapsByUserRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListYapsByUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUser provides a mock function with given fields: ctx, arg
func (_m *Querier) NewUser(ctx context.Context, arg repository.NewUserParams) (string, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for NewUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.NewUserParams) (string, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.NewUserParams) string); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.NewUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrphanMedia provides a mock function with given fields: ctx, arg
func (_m *Querier) OrphanMedia(ctx context.Context, arg repository.OrphanMediaParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for OrphanMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.OrphanMediaParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDeleteMedia provides a mock function with given fields: ctx, mediaID
func (_m *Querier) SoftDeleteMedia(ctx context.Context, mediaID pgtype.UUID) error {
	ret := _m.Called(ctx, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) error); ok {
		r0 = rf(ctx, mediaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEmail provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateEmail(ctx context.Context, arg repository.UpdateEmailParams) (repository.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmail")
	}

	var r0 repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateEmailParams) (repository.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateEmailParams) repository.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateEmailParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMediaContent provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateMediaContent(ctx context.Context, arg repository.UpdateMediaContentParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMediaContent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateMediaContentParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePassword provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdatePassword(ctx context.Context, arg repository.UpdatePasswordParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdatePasswordParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateUser(ctx context.Context, arg repository.UpdateUserParams) (repository.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateUserParams) (repository.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateUserParams) repository.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateYap provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateYap(ctx context.Context, arg repository.UpdateYapParams) (repository.UpdateYapRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateYap")
	}

	var r0 repository.UpdateYapRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateYapParams) (repository.UpdateYapRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateYapParams) repository.UpdateYapRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.UpdateYapRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateYapParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
